NAME = '晓英'
VERSION = '2024.4'
AUTHOR = '人山'
WEBSITE = 'https://www.fogbud.com'
EMAIL = 'orchid.x@outlook.com'
LICENSE = 'GPL-3.0'
SOURCE = 'https://github.com/w-sx/xiaoying'
#PROJECT = 'https://www.fogbud.com/xiaoying'